### ISSUE TITLE
ReST API documentation not found

### ISSUE THREAD

**Issue by cyluxx** [LearnLib/alex#12]
I tried to open the ReST documentation as described [here](http://learnlib.github.io/alex/book/1.5.0/contents/developer-documents/REST.html). (There does not seem to exist a 1.6.0 documentation version for ALEX, is that correct?)

However, I get the following error message:

> Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Fri Oct 19 16:36:20 CEST 2018
There was an unexpected error (type=Not Found, status=404).
No message available

Version: ALEX 1.6.0
System: Windows 10

**Comment by abainczyk** [comment]
Hi, I haven't updated this site yet. There is no documentation of the REST API (anymore), but I plan to write one in the near future again.
