### ISSUE TITLE
Saving actions

### ISSUE THREAD

**Issue by Jaxan** [LearnLib/alex#2]
We gave a tutorial on ALEX at the BSR winter school. Some issues popped up.

It's too easy to forget to save the actions for a symbol. When you go back or to another page, you get this message "Are you sure you want to leave?" With two buttons (Yes/No). It's easy to mistake it with the question "Do you want to save?", like any other piece of software does.

So I think it would be good to replace that message with "Do you want to save" with three buttons: Yes/No/Cancel.

**Comment by abainczyk** [comment]
Sounds like a reasonable UX enhancement to me. I will implement it soon. Thanks!
