### ISSUE TITLE
Firefox Web Driver not saved

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#28]
# Version
Alex Version: 1.7.2
Browser: Firefox 68

# Problem
Firefox cannot be selected as Default Web Driver

# Steps to reproduce:
1. Open Alex, Login as Admin
2. Click "Settings" in the left menu
3. Choose Firefox as Default Web Browser (Blue/green "Default"-Button on the right)
4. Click Save. Green PopUp "The settings have been updated" appears
5. Firefox seems to be the default Web Driver
6. Reload Page -> "HTML Unit" is selected as Default Web Driver :(

The Path to the geckodriver is set

**Comment by abainczyk** [comment]
Should be fixed with 1f1af346814e2ebe69f2e227d95a8b76fffa422a
