### ISSUE TITLE
Unsaved Test-Cases are passed

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#32]
Steps to reproduce:

1. Create a new test case
2. Add any symbol
3. Dont save!
4. Click on Execute
5. Message "The test case passed." appears but no smybol has been executed

A warning is displayed if you try to execute a test-case without any symbol. But there is no warning or auto-save if you add a symbol and execute without a save.

I think the Execute-Button should automaticly save the current test-case. Alternatively, at least a warning should be displayed.

**Comment by abainczyk** [comment]
Nice idea, implemted your suggestion to save a test case automatically before executing it in 726dc97dc89ffd17088af1b1973fc286d6a0021d
