### ISSUE TITLE
Execution of a single test-case is not added to the queue

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#33]
Execute a test-case:

1. Click at the menu item "Manage" in the category "Testing"
2. Select a single test-case
3. Page with a single test-case and the assigned symbols is displayed
4. Click on "Execute"

The test-case is executed but there is no chance to abort the execution of the test-case. Sometimes some symbols hang and there is no option to abort them.
Another problem is that if you open another (Alex-)page or reload the current page we have no information that a test-case is beeing executed.

I can image three possible solutions:
1. If we run multiple test cases, they will be queued and the status of the tests will be displayed even after reloading the page. Maybe you could use that queue for a single test-case as well?
2. Implement an abort button which should be visible after reloading the page as well
3. if this is too hard: Implement an abort button which is visible until reload

**Comment by abainczyk** [comment]
I am aware of the issue and will most likely implement it like you suggested in 1.
