### ISSUE TITLE
Add ability to save configuration for Remote Selenium Server

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#34]
We use the Remote Selenium Server. Under Settings we can set Remote Selenium Server as default Web driver.

But if we execute a single test-case we have to reconfigure the settings for the WebDriver every time (e.g. Use headless mode, Browser, Width and Height, Timeouts...)

![alex-remote-driver-settings](https://user-images.githubusercontent.com/15267677/66517397-5f5e4480-eae3-11e9-9971-89466aba1682.JPG)

These settings are lost if we reload the page or select antoher test-case. Is it possible to save these settings permanently? Maybe for all test-cases?

**Comment by abainczyk** [comment]
Hi, we are currently having the same issue as you have. Since we can already save test configurations in the view where all the tests are displayed, I plan on giving users the option to mark one of them as default and use it where it is needed without having to reconfigure it every time.

**Comment by abainczyk** [comment]
implemented in fa8bb5f721fe14174774b53251f8bc00f2fdeff4
