### ISSUE TITLE
Add an option to rename test-suites

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#35]
1. Click on Manage (category Testing)
2. Select an exisiting test-suite
3. There is no button for renaming an exisiting test-suite

**Comment by abainczyk** [comment]
Well, there is an option to rename a test suite in the dropdown menu on the right of each test suite in the list. However, I added an "edit" button in the action bar for convenience with b06e673fd1fbf88edc5bd2505ee77d29aa3ac9b3.
