### ISSUE TITLE
Symbol "Make request" doesnt work

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#36]
We updated from an unknown older version to the version of the dev-Branch from yesterday afternoon. Both version-strings are 1.8.0-SNAPSHOT. Since the update the "Make request"-Symbol doesn't work any more.

Steps to reproduce:

1. Create an "Debug" symbol
2. Add the "Make-Request" Action
3. Select a valid Base-URL and enter an url (Maybe this is not important but we didn't choose the default base-url)
4. Select GET as method (should be the same error for any other HTTP-Method. At least Get and Post doesn't work)
5. Create the action
6. Create action "Check status", use HTTP Status 200
7. Save the symbol
8. Create a test-case with the new symbol
9. Save the symbol
10. Configure the test configuration (see below)
11. Execute the test-case

The test-case will be failed at the symbol, action 2. If we execute the same request from our local machines (e.g. with Insomnia or Postman), the request works quite well.

Test-Configuration:
![alex-test-config](https://user-images.githubusercontent.com/15267677/66598555-9004b380-eba1-11e9-8405-56db55b6cfa5.JPG)

**Comment by abainczyk** [comment]
Could you please show me what your "make request" action looks like? Have you entered an absolute URL?

**Comment by Benuhx** [comment]
Sure! We're using relativ URLs.

Make-Request:
The sections Authentification and Cookies are empty.
![alex-make-request-1](https://user-images.githubusercontent.com/15267677/66604216-00193680-ebae-11e9-9a3a-1e2326cdb7a1.JPG)

Our base URLs:
![alex-make-request-2](https://user-images.githubusercontent.com/15267677/66604037-9ac54580-ebad-11e9-84ab-f3d31cc86146.JPG)

**Comment by Benuhx** [comment]
Fixed with newest Version 1.8.0-SNAPSHOT :)
