### ISSUE TITLE
Invalid driver configuration is not reported properly

### ISSUE THREAD

**Issue by MazeChaZer** [LearnLib/alex#37]
This is related to #19. I expected the configuration to be saved between runs, but it wasn't, so my configuration was `"driver": "remote", "browser": null`. This is an invalid config, but instead of getting a proper error message ALEX only showed that the first step in each action is failing. I wasted quite some time suspecting that the reset api was somehow broken. A better error message would help here.

**Comment by abainczyk** [comment]
Should be fixed in 9525edbe11f00aa6057f2d8c3ccaf15e8a4a447a
