### ISSUE TITLE
Docker Image - Remote Debug

### ISSUE THREAD

**Issue by SinaDBMS** [LearnLib/alex#39]
Hi,

it would be helpful when we could run the ALEX in debug mode. Probably via an environment variable set as a flag in the _docker run_ command.

**Comment by abainczyk** [comment]
Implemented in e4e0ebd341a7596ea881576ee2ae3a9e7d921cf3. Run ALEX using the docker-compose.develop file and configure your IDE like this: 
![Bildschirmfoto vom 2021-07-20 15-28-59](https://user-images.githubusercontent.com/14344841/126332584-633bab09-e754-4d57-a912-e8d662a538c1.png)
