### ISSUE TITLE
Cache problem?

### ISSUE THREAD

**Issue by Jaxan** [LearnLib/alex#4]
We gave a tutorial on ALEX at the BSR winter school. Some issues popped up.

This is directly from one of the students, he didn't show me the issues, just send this via email:

> There’s a cache problem. When I run multiple learning runs I seem to get the same result back (takes long the first time, is quick every time after). I need to delete the results under Learning/Results to make it run with the updated project.

Maybe he used the wrong buttons (continue instead of start learning). But since I didn't see it, I don't know.

**Comment by abainczyk** [comment]
We don't cache old results for new test runs. If for the same learn experiment, the results pops up almost immediately, it is most likely, as you said, that the user clicked on the "continue" button. I'll think about how one can make this more clear to a user. Thanks!
