### ISSUE TITLE
Categorize LTL formulas

### ISSUE THREAD

**Issue by lmoellering** [LearnLib/alex#43]
Hi,
it is difficult to categorize the LTL formulas.
It would be nice to have an Interface, similar to the Testing Interface, to build Check Suites.
It should offer the possibility to Group Temporal Logic Formulas into Checksuites with an expected outcome, a description and related automata.

**Comment by abainczyk** [comment]
Implemented in 10160825e3376ca0c944f2ac07d12d18d558dba7
