### ISSUE TITLE
Bug: Project import fails with 401

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#51]
I've updated my local Alex Enviroment to the latest Docker-Version from learnlib/alex:unstable avaibale at 26.11.2019 23:00 Uhr.
After the update i cannot import projects anymore.

Steps to reproduce:
- Export Project or use this one (just rename to .json):  [GC.txt](https://github.com/LearnLib/alex/files/3894297/GC.txt)
- Login to another Alex Instance with default credentials. User admin@alex.example and Pwd admin
- Click on the Import-Button
- Select the previously exported filed
- Click Import
- Error msg "The project could not be imported. You could not be authenticated." appears and you're redirected to the login page :(

Firefox shows that the import POST-request to 'http://localhost:8000/rest/projects/import' has the following json repsonse:
{"timestamp":"2019-11-26T22:44:20.203+0000","status":401,"error":"Unauthorized","message":"You could not be authenticated.","path":"/rest/projects/import"}

Full Exception and Stacktrace from docker-compose logs:
[alex_import_logs.txt](https://github.com/LearnLib/alex/files/3894325/alex_import_logs.txt)

Maybe this is related to #50 ?

**Comment by abainczyk** [comment]
Could you please check if your `ClickAndWaitFor` symbol that is in the archive has any input parameters? It seems that they are not being exported. You could, in the meantime, remove anything related to the symbol from the JSON file and the import will work fine. Not related to #50

**Comment by Benuhx** [comment]
The ClickAndWaitFor symbol in the archive (exact name is ClickAndWaitFor--20191125-07:53:57) does not have any input parameters. There are no steps, completly empty:
![G1](https://user-images.githubusercontent.com/15267677/69761568-11230480-1168-11ea-819b-792ec926a2bc.JPG)

However we have an ClickAndWaitFor Symbol which is not in the archive and this one has 2 input parameters. Could not find this one in the JSON:
![G2](https://user-images.githubusercontent.com/15267677/69761574-154f2200-1168-11ea-9894-22af7ac9675a.JPG)

Import works after removing ClickAndWaitFor--20191125-07:53:57 symbol :)

**Comment by abainczyk** [comment]
There were some issues in the database where rows contained unexpected null values. This should not happen anylonger as of 19779d15116279f7f9248ab780ece811b3bcd21f
