### ISSUE TITLE
Copy & paste test case steps

### ISSUE THREAD

**Issue by hkloe** [LearnLib/alex#55]
Hi,

when creating a test it would be helpful to have the possibility to copy/paste selected Symbols. (To replicate groups of Symbols in a test or resuse parameters for similar symbol executions)

**Comment by hkloe** [comment]
Also it would be nice to have a description/comment field at the tests.

**Comment by abainczyk** [comment]
> Also it would be nice to have a description/comment field at the tests.

I feel like this should be a separate issue #57. I also renamed this issue to better reflect its initial intent.

**Comment by abainczyk** [comment]
Will close this because we probably will not implement this anytime soon.
