### ISSUE TITLE
Project import fails with 401

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#59]
Version: Latest docker image avaible at 04.12.19 / 15:00 Uhr (both on export and import instance)

Similar (or the same) issue as #51 

**Steps to reproduce:**

- Export Project or use this one (just rename to .json):  [GC041219.txt](https://github.com/LearnLib/alex/files/3924187/GC041219.txt)

- Login to another Alex Instance with default credentials. User admin@alex.example and Pwd admin
- Click on the Import-Button
- Select the previously exported filed
- Click Import
- Error msg "The project could not be imported. You could not be authenticated." appears and you're redirected to the login page :(

**Full Exception and Stacktrace from docker-compose logs:**
[GC_Import_Export_041219.txt](https://github.com/LearnLib/alex/files/3924194/GC_Import_Export_041219.txt)

**Comment by abainczyk** [comment]
Sorry this happened again. After deleting `MailcatcherGetKeyAndLink--20191125-07:53:57` I was able to import the project again. Since the symbol is in the archive, it would propably be a good idea to delete it permanently so that export / import works properly.

**Comment by Benuhx** [comment]
Import / Export works after deleting MailcatcherGetKeyAndLink--20191125-07:53:57 from the archive

**Comment by abainczyk** [comment]
I could not reproduce this issue with other projects and exported symbols from the archive. if this issue persists, please open a new issue.
