### ISSUE TITLE
Cloning symbols

### ISSUE THREAD

**Issue by Jaxan** [LearnLib/alex#6]
Hi again :),

One of the students was a bit bothered by the amount of work it requires to define a symbol. Now, often symbols are very similar. So it would be nice to have a button to copy a symbol, so that you just apply the differences.

**Comment by abainczyk** [comment]
We already have the possibility to copy/cut and paste all or a subset of the actions from a symbol into another one for that case. We will reflect the idea of adding a dedicated button for that, thank you.

**Comment by Jaxan** [comment]
I tried to find it, but couldn't. See maybe it's just a visibility issue. Great to hear the functionality is already there!

**Comment by abainczyk** [comment]
If you still have trouble finding this: If you are in the view where you create actions for a symbol, there is a dropdown menu with the label '...' right to the create, edit, delete buttons. There you can find the cut/copy and paste functionality for actions. Make sure to select the actions you want to cut/copy first.

**Comment by abainczyk** [comment]
For now, we think the copy/paste options for actions are placed prominently enough. So I close this issue.
