### ISSUE TITLE
Symbol search does not find symbols in Subgroup

### ISSUE THREAD

**Issue by Benuhx** [LearnLib/alex#60]
Version: Latest docker image avaible at 05.12.19 / 11:00 Uhr
Browser: Firefox 70.0.1

Steps to reproduce:
1. Login
2. Click Manage Symbols
3. Try the search function:
-> Symbols in a group e.g. API Calls are found (black in screenshot)
-> Symbols in a sub group e.gh. API Calls / SQL Posts are NOT found (red in screenshot)
![Alex_search](https://user-images.githubusercontent.com/15267677/70269738-40a6c200-17a3-11ea-99df-947081430f1e.JPG)

**Comment by abainczyk** [comment]
fixed with aa2af1e0224f3425f0ea579ec31edc9f3deb5dcb
