### ISSUE TITLE
Resume learning with counterexample

### ISSUE THREAD

**Issue by lmoellering** [LearnLib/alex#62]
Hi,

if I have added a counterexample and want to resume learning, the following error message appears:

![image](https://user-images.githubusercontent.com/24420295/70419672-336d2a00-1a66-11ea-95be-3f8f2fa79ef5.png)

The test number is the same, which one receives by the http request ../results/latest and the project id is also correct.

**Comment by abainczyk** [comment]
Hi, sorry but I cannot reproduce this error. Please provide an example or the concrete steps to reproduce this.

**Comment by abainczyk** [comment]
is this still an issue?

**Comment by lmoellering** [comment]
is fixed.
