### ISSUE TITLE
Could not load image 'foo.svg'

### ISSUE THREAD

**Issue by fetchandadd** [LearnLib/alex#67]
Eye of MATE (Version 1.20.0) fails to open an exported (SVG) result.

> Error domain 1 code 9 on line 7 column 1255 of foo.svg: Input is not proper UTF-8, indicate encoding !
Bytes: 0xFC 0x63 0x6B 0x20

**Comment by abainczyk** [comment]
fixed in 9ab3616d3c68da0e1fbcdabd7796b11aaee41272

**Comment by fetchandadd** [comment]
@abainczyk Nice!
