### ISSUE TITLE
Resume Learning with non-default environment

### ISSUE THREAD

**Issue by lmoellering** [LearnLib/alex#73]
If I want to resume a learning process that started with a non-default environment, for example by giving a counterexample, this will be done with the default environment.

**Comment by abainczyk** [comment]
Fixed in ea1c942f0036f879cbec9965cf54b2ced5b525c1

The problem was more that the specified counterexample was tested on the default environment rather than on one specified in the setup. The learning process itsself however resumed with the correct environment.
