### ISSUE TITLE
'--port' Argument ignored when starting ALEX from .war file

### ISSUE THREAD

**Issue by MartijnVerkleij** [LearnLib/alex#8]
What I did:
Executed `java -jar ./Downloads/ALEX-1.3.0.war --port=8005`, which should be identical to the instructions on [https://learnlib.github.io/alex/](url)

Expected behaviour:
A tomcat server running ALEX should be started on localhost:8005

Actual behaviour:
A tomcat server running ALEX is started on localhost:8000

This was tested on Ubuntu 16.04.

**Comment by abainczyk** [comment]
You are totally right. It should be `--alex.port=XXXX`. So in your case it would be `java -jar ./Downloads/ALEX-1.3.0.war --alex.port=8005`. I will update it on the homepage.

**Comment by abainczyk** [comment]
I have updated the website accordingly.
