### ISSUE TITLE
Make learner setups addressable by name

### ISSUE THREAD

**Issue by MazeChaZer** [LearnLib/alex#85]
In a CI context, it would be useful if learner setups could be addressed by name instead of the ID. Like

```bash
alex-cli \
    --uri "http://alex" \
    --do "learn" \
    --user "admin@alex.example:admin" \
    --project "project.json" \
    --config "config.learning.json" \
    --setup "order-process" \
    --clean-up
```

This command would start the learning setup named "order-process".

**Comment by abainczyk** [comment]
Do you still need the `--config` argument if the learner setup is included in the `project.json` file and thus imported? The learner setup should include all information that is also included in the `config.learning.json` file.
.

**Comment by abainczyk** [comment]
You can now use the CLI like this:

```bash
node alex-cli.js \
        --uri "http://localhost:8000" \
        --do "learn" \
        --user "admin@alex.example:admin" \
        --project "project.json" \
        --setup "order-process" \
        --clean-up
```
