### ISSUE TITLE
Support CI integration

### ISSUE THREAD

**Issue by MazeChaZer** [LearnLib/alex#86]
This is how we envision a CI script that would run e.g. on GitLab CI:

```bash
#!/usr/bin/env bash
set -euxo pipefail

cd alex-pipeline/

mkdir learning-results/

ltl_hold=$(true)
while read aspect; do
    alex-cli \
        --uri "http://alex-backend:8000" \
        --do "learn" \
        --user "admin@alex.example:admin" \
        --project "project.json" \
        --config "config.learning.json" \
        --setup "${aspect}" \
        --output "learning-results/${aspect}.json" \
        --clean-up

    ltl_hold=\
        alex-cli \
            --uri "http://alex-backend:8000" \
            --do "check" \
            --user "admin@alex.example:admin" \
            --project "project.json" \
            --config "config.learning.json" \
            --ltl-group "${aspect}" \
            --model "learning-results/${aspect}.json" \
            --clean-up \
                && ltl_hold
done < aspects.txt

if ! ltl_hold; then
    echo "LTL failures"
    exit 1
fi

fetch_artifacts

while read aspect; do
    if artifact_exists; then
        alex-cli \
            --uri "http://alex-backend:8000" \
            --do "compare" \
            --user "admin@alex.example:admin" \
            --model1 "${model_from_gitlab_artifacts}" \
            --model2 "learning-results/${aspect}.json" \
            --output "model-difference-${aspect}.json"

        if difference_non_empty; then
            create_issue
        fi
    fi
done < aspects.txt
```
We would need:
- Adressing learning setups by name (#85)
- Checking LTL formula suite by a given name for an uploaded model
- Compare two uploaded models and store the difference in a file

**Comment by abainczyk** [comment]
I think we could combine the first two cli calls, or is the strict separation necessary? Currently, if you specify ltl formulas with the `--formulas` argument, the learned model is immediately checked and the cli returns 0 or 1 depending if all ltl properties hold. I think this would be enough:

```
ltl_hold=\
    alex-cli \
        --uri "http://alex-backend:8000" \
        --do "learn" \
        --user "admin@alex.example:admin" \
        --project "project.json" \
        --setup "${aspect}" \
        --ltl-suite "${aspect}" \
        --output "learning-results/${aspect}.json" \
        --clean-up
```

**Comment by abainczyk** [comment]
We wouldn't event require the `--ltl-suite "${aspect}"` argument here if LTL suites could be associated to learner setups as proposed in #82, right?

**Comment by MazeChaZer** [comment]
Yeah I think we can combine the first two invocations, as long as the learned model is still written to a file. Right, the `--ltl-suite` argument wouldn't be needed anymore with #82.

**Comment by abainczyk** [comment]
With the changes introduced in 6d8fc7d1b4fe8cb264c2bb8efefa2d593608bf9e, 9525edbe11f00aa6057f2d8c3ccaf15e8a4a447a and ff987a33b1017d8cc8984c26ad5a8e16a3103e43 it is now possible to associate multiple LTL suites with a learner setup. If suites have been configured for a learner setup, models are automatically model checked and a report is created.

These changes are reflected in the CLI as well. The success of the CLI invocation now depends on the successful execution of the model checker. As we discussed above, we do not require an additional `--ltl-suite` argument, so the invocation would look like this for the learning part:

```bash
alex-cli \
  --uri "http://alex-backend:8000" \
  --do "learn" \
  --user "admin@alex.example:admin" \
  --project "project.json" \
  --setup "${aspect}" \
  --output "learning-results/${aspect}.json" \
  --clean-up
```
The comparison of two learned models also works now. The invocation would look like this:

```bash
alex-cli \
  --uri "http://alex-backend:8000" \
  --do "compare" \
  --user "admin@alex.example:admin" \
  --models "${model_from_gitlab_artifacts}" "learning-results/${aspect}.json" \
  --output "model-difference-${aspect}.json"
```

Please let me know if that works for you and close the issue if it does.
